#--------------------------------------------------------------------------
# docker image for CLAS12 Production Simulation to use interactively.
#
# It is based on gemcinteractive:2.7 image and includes:
#
# - JLAB_VERSION 2.3
# - clas12 tag 4a.2.5
# - clara 4.3.3
# - coatjava 5b.7.1
# - clasdis generator
#
# The tag of this version is iprod
#
#  1. Remember to find/replace gemcinteractive with the newest one
#  2. Remember to match clas12tags and JLAB_VERSION in environment.csh
#  3. Remember to find/replace COATJTAG with the newest one
#
#
# To build manually:
#
#   docker build -f Dockerfile-interactive -t clas12simulations:iprod .
#
#   docker tag clas12simulations:iprod maureeungaro/clas12simulations:iprod
#
#   docker push maureeungaro/clas12simulations:iprod
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#   docker run -it --rm maureeungaro/clas12simulations:iprod bash
#
# On a mac, if you allow access from localhost with:
#
#  1. Activate the option ‘Allow connections from network clients’ in XQuartz settings
#  2. defaults write org.macosforge.xquartz.X11 enable_iglx -bool true
#     (Restart XQuartz (to activate the setting)
#  3. xhost +127.0.0.1
#
# Then you can run docker and use the local X server with:
#
#  docker run -it --rm -e DISPLAY=docker.for.mac.localhost:0 maureeungaro/clas12simulations:iprod bash
#--------------------------------------------------------------------------

FROM jeffersonlab/gemcinteractive:2.7
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION 2.3
ENV CLAS12TAG 4a.2.5
ENV COATJTAG 5b.7.1

# gfortran for clasdis generator
# xemacs to help users
# libXtst for kpp-plots
# libfonts for kpp-plots fonts
RUN yum install -y gcc-gfortran xemacs libXtst libfonts

WORKDIR $JLAB_ROOT

# Removing un-used tags and .git stuff
# Removing default version of gemc
# Replacing the scripts in /etc and with the environment scripts
# Checking out clas12Tags and compiling CLAS12TAG
# Putting clas12 gcard in $JLAB_ROOT/work
# Getting the field maps
# $JLAB_ROOT/work is an existing directory
RUN git clone https://github.com/gemc/clas12Tags.git \
	&& cd $JLAB_ROOT/clas12Tags \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& rm -rf $JLAB_ROOT/$JLAB_VERSION/$OSRELEASE/gemc \
	&& ./goInstall $CLAS12TAG \
	# delete .git after goInstall as it does a pull
	&& rm -rf .git* `ls | grep -v goIns | grep -v $CLAS12TAG | grep -v env | grep -v REA` \
	&& cp $JLAB_ROOT/clas12Tags/$CLAS12TAG/clas12.gcard $JLAB_ROOT/work \
	&& mkdir -p /jlab/noarch/data \
	&& cd /jlab/noarch/data \
	&& wget -q http://clasweb.jlab.org/12gev/field_maps/TorusSymmetric.dat \
	&& wget -q http://clasweb.jlab.org/12gev/field_maps/clas12NewSolenoidFieldMap.dat \
	&& rm /etc/profile.d/jlab.csh \
	&& rm /etc/profile.d/jlab.sh \
	# reconstruction, clara and coatjava
	&& mkdir -p $JLAB_SOFTWARE/clas12/lib \
	&& mkdir -p $JLAB_SOFTWARE/clas12/bin \
	&& mkdir -p $JLAB_SOFTWARE/clas12/inc \
	&& export CLARA_HOME=$JLAB_ROOT/$JLAB_VERSION/claraHome \
	&& mkdir -p $CLARA_HOME /jlab/tmp \
	&& cd /jlab/tmp \
	&& wget  --no-check-certificate https://claraweb.jlab.org/clara/_downloads/install-claracre-clas.sh \
	&& chmod u+x install-claracre-clas.sh \
	&& ./install-claracre-clas.sh -v $COATJTAG \
	&& cd /jlab \
	&& rm -rf tmp \
	# the following comands create a dst directory (which must be pointed to in the yaml file)
	# with a subset of the banks, thus effectively creating a dst schema
	&& cd /jlab/2.3/claraHome/plugins/clas12/etc/bankdefs \
	&& mkdir dst \
	&& cd hipo \
	# copying all banks in the interactive reconstruction. New services.yaml points to dst dir for the list of banks
	&& cp *.json ../dst/ \
	# && cp  HEADER.json MC.json EVENT.json ../dst/
	&& rm /jlab/2.3/claraHome/plugins/clas12/config/services.yaml \
	# temp removal of this jar
	&& rm /jlab/2.3/claraHome/plugins/clas12/lib/utils/jclara-4.3-SNAPSHOT.jar \
	# clasdis generator
	&& cd /jlab/work \
	&& git clone https://github.com/JeffersonLab/clasdis-nocernlib \
	&& cd clasdis-nocernlib \
	&& make \
	&& cp clasdis $JLAB_SOFTWARE/clas12/bin \
	# inclusive dis with radiative correction
	&& cd /jlab/work \
	&& git clone https://github.com/JeffersonLab/inclusive-dis-rad.git \
	&& cd inclusive-dis-rad \
	&& make \
	&& cp generate-dis $JLAB_SOFTWARE/clas12/bin \
	# clasdvcs
	&& cd /jlab/work \
	&& git clone https://github.com/JeffersonLab/dvcsgen.git \
	&& cd dvcsgen \
	&& make \
	&& cp dvcsgen $JLAB_SOFTWARE/clas12/bin



ADD environment.csh     /etc/profile.d
ADD environment.sh      /etc/profile.d
ADD services.yaml       /jlab/2.3/claraHome/plugins/clas12/config
ADD services.yaml       /jlab/2.3/claraHome/plugins/clas12/config
ADD createClaraCook.csh /jlab/2.3/Linux_CentOS7.5.1804-x86_64-gcc4.8.5/clas12/bin

WORKDIR $JLAB_ROOT/work
